name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      pgdocker: ${{ steps.check.outputs.pgtag }}
      buildpgdocker: ${{ steps.check.outputs.buildpg }}

    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: mainfilter
      with:
        filters: |
          main:
            - 'docker/pgstac/**'
    - uses: dorny/paths-filter@v2
      id: headfilter
      with:
        base: HEAD^
        filters: |
          head:
            - 'docker/pgstac/**'
    - id: check
      run: |
        buildpg=false;
        ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}};
        if [[ ${{ steps.mainfilter.outputs.main }} == 'true' ]]; then
          ref=latest
        elif [[ ${{ steps.headfilter.outputs.base }} == 'true' ]]; then
          buildpg=true;
        fi;
        echo "pgdocker=${{ env.REGISTRY }}/pgstac-pg:$pgtag" >>$GITHUB_OUTPUT;
        echo "buildpgdocker=$buildpg" >>$GITHUB_OUTPUT;

  # currentchanges:
  #   runs-on: ubuntu-latest
  #   # Required permissions
  #   permissions:
  #     pull-requests: read
  #   # Set job outputs to values from filter step
  #   outputs:
  #     postgres: ${{ steps.filter.outputs.postgres }}
  #     ref: ${{ github.ref.name }}
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: dorny/paths-filter@v2
  #     id: filter
  #     with:
  #       base: HEAD^
  #       filters: |
  #         postgres:
  #           - 'docker/pgstac/**'

  # changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     pgtag: ${{ steps.check.outputs.pgtag }}
  #     buildpg: ${{ steps.check.outputs.buildpg }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - id: check
  #       run: |
  #         git fetch origin main;
  #         buildpg=false;
  #         pgtag=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}};
  #         if ! git diff --stat main -- docker | head -c1 | grep -E '.'; then
  #           pgtag=latest;
  #         elif git diff --stat HEAD^ -- docker | head -c1 | grep -E '.'; then
  #           buildpg=true;
  #         fi;
  #         echo "pgtag=${{ env.REGISTRY }}/pgstac-pg:$pgtag" >>$GITHUB_OUTPUT;
  #         echo "buildpg=$buildpg" >>$GITHUB_OUTPUT;
  #     - id: show
  #       run: |
  #         echo "${{ steps.check.outputs.pgtag }}"
  #         echo "${{ steps.check.outputs.buildpg }}"


  buildpg:
    name: Build and push base postgres
    if: ${{ needs.changes.outputs.buildpg == 'true' }}
    runs-on: ubuntu-latest
    needs: [changes]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Base Postgres
        uses: docker/build-push-action@v4
        with:
          context: .
          target: pgstacbase-plrust
          file: docker/pgstac/Dockerfile
          tags: ${{ needs.changes.outputs.pgtag }}
          push: true
          cache-from: type=gha
          cache-to: type=gha, mode=max

  buildpypgstac:
    name: Build pypgstac wheel with Maturin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: PyO3/maturin-action@v1
        with:
          working-directory: src/pypgstac
          args: --release --out /tmp/dist
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: /tmp/dist
          if-no-files-found: error

  test:
    name: test
    needs: [buildpypgstac, changes, buildpg]
    runs-on: ubuntu-latest
    container: python:3-slim-bullseye

    services:
      postgres:
        image: ${{ needs.changes.outputs.pgtag }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: /tmp/wheels
      - name: Install pypgstac from wheel
        run:  |
          find /tmp/wheels/*.whl -exec pip install '{}[dev,test,psycopg]' \;
      - name: Run tests
        working-directory: src/pypgstac
        env:
          PGPASSWORD: lksjfalkjewkjrw
          PGHOST: postgres
          PGDATABASE: postgres
          PGUSER: postgres
        run:  |
          pytest -vvv


      # - uses: docker/setup-buildx-action@v2
      # - name: docker-compose-build
      #   run: docker buildx bake --file docker-compose.yml --file docker-compose-cache.json
      # - name: test
      #   id: test
      #   run: scripts/test
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: docker/pgstac/Dockerfile
      #     load: true
      #     push: false
      #     cache-from: type=gha
      #     cache-to: type=gha, mode=max
      # - name: pypgstacbuilder
      #   id: pypgstacbuilder
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: docker/pypgstac/Dockerfile
      #     load: true
      #     push: false
      #     cache-from: type=gha
      #     cache-to: type=gha, mode=max

      # - name: Start Database
      #   run: docker run -d --rm -e POSTGRES_PASSWORD=pg --expose 5432 ${{ steps.pgstacbuilder.outputs.imageid }}

      # - name: Database Ready
      #   run: docker exec ${{ steps.pgstacbuilder.outputs.imageid }} pg_isready

      # - name: Run tests
      #   run: docker run --rm -e PGUSER=postgres -e PGDATABASE=postgres -e PGPASSWORD ${{ steps.pypgstacbuilder.outputs.imageid }} /opt/docker/pypgstac/bin/test
