name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build PGStac Docker
        run: docker buildx build --cache-from=type=gha --cache-to=type=gha,mode=max --tag=pgstac .


      - name: Run tests
        run: docker run --rm  pgstac test
