name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        id: builder
        with:
          context: .
          tags: pgstac
          publish: false
          cache-from: type=gha
          cache-to: type=gha, mode=max

      - name: Run tests
        run: docker run --rm  ${{ steps.builder.outputs.imageid }}  test
